// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>Royal.Walmart.Api</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Flexi.Model.Poco.Walmart.Api
{
    using System.Collections.Generic;
    using System.Xml.Serialization;

    [XmlRoot("PartnerFeedResponse", Namespace = "http://walmart.com/")]
    public partial class PartnerFeedResponse
    {

        private string feedIdField;

        private FeedStatus feedStatusField;

        private List<IngestionError> ingestionErrorsField;

        private int itemsReceivedField;

        private bool itemsReceivedFieldSpecified;

        private int itemsSucceededField;

        private bool itemsSucceededFieldSpecified;

        private int itemsFailedField;

        private bool itemsFailedFieldSpecified;

        private int itemsProcessingField;

        private bool itemsProcessingFieldSpecified;

        private int offsetField;

        private bool offsetFieldSpecified;

        private int limitField;

        private bool limitFieldSpecified;

        private List<PartnerItemIngestionStatus> itemDetailsField;

        public PartnerFeedResponse()
        {
            this.itemDetailsField = new List<PartnerItemIngestionStatus>();
            this.ingestionErrorsField = new List<IngestionError>();
        }

        public string feedId
        {
            get
            {
                return this.feedIdField;
            }
            set
            {
                this.feedIdField = value;
            }
        }

        public FeedStatus feedStatus
        {
            get
            {
                return this.feedStatusField;
            }
            set
            {
                this.feedStatusField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("ingestionError", IsNullable = false)]
        public List<IngestionError> ingestionErrors
        {
            get
            {
                return this.ingestionErrorsField;
            }
            set
            {
                this.ingestionErrorsField = value;
            }
        }

        public int itemsReceived
        {
            get
            {
                return this.itemsReceivedField;
            }
            set
            {
                this.itemsReceivedField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool itemsReceivedSpecified
        {
            get
            {
                return this.itemsReceivedFieldSpecified;
            }
            set
            {
                this.itemsReceivedFieldSpecified = value;
            }
        }

        public int itemsSucceeded
        {
            get
            {
                return this.itemsSucceededField;
            }
            set
            {
                this.itemsSucceededField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool itemsSucceededSpecified
        {
            get
            {
                return this.itemsSucceededFieldSpecified;
            }
            set
            {
                this.itemsSucceededFieldSpecified = value;
            }
        }

        public int itemsFailed
        {
            get
            {
                return this.itemsFailedField;
            }
            set
            {
                this.itemsFailedField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool itemsFailedSpecified
        {
            get
            {
                return this.itemsFailedFieldSpecified;
            }
            set
            {
                this.itemsFailedFieldSpecified = value;
            }
        }

        public int itemsProcessing
        {
            get
            {
                return this.itemsProcessingField;
            }
            set
            {
                this.itemsProcessingField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool itemsProcessingSpecified
        {
            get
            {
                return this.itemsProcessingFieldSpecified;
            }
            set
            {
                this.itemsProcessingFieldSpecified = value;
            }
        }

        public int offset
        {
            get
            {
                return this.offsetField;
            }
            set
            {
                this.offsetField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool offsetSpecified
        {
            get
            {
                return this.offsetFieldSpecified;
            }
            set
            {
                this.offsetFieldSpecified = value;
            }
        }

        public int limit
        {
            get
            {
                return this.limitField;
            }
            set
            {
                this.limitField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool limitSpecified
        {
            get
            {
                return this.limitFieldSpecified;
            }
            set
            {
                this.limitFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("itemIngestionStatus", IsNullable = false)]
        public List<PartnerItemIngestionStatus> itemDetails
        {
            get
            {
                return this.itemDetailsField;
            }
            set
            {
                this.itemDetailsField = value;
            }
        }
    }

    public enum FeedStatus
    {

        /// <remarks/>
        RECEIVED,

        /// <remarks/>
        INPROGRESS,

        /// <remarks/>
        PROCESSED,

        /// <remarks/>
        ERROR
    }

    public partial class IngestionError
    {

        private ErrorType typeField;

        private string codeField;

        private string descriptionField;

        public ErrorType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    public enum ErrorType
    {

        /// <remarks/>
        DATA_ERROR,

        /// <remarks/>
        SYSTEM_ERROR,

        /// <remarks/>
        TIMEOUT_ERROR,
    }

    public partial class PartnerItemIngestionStatus
    {

        private int martIdField;

        private bool martIdFieldSpecified;

        private string skuField;

        private string wpidField;

        private int indexField;

        private bool indexFieldSpecified;

        private ItemStatus ingestionStatusField;

        private List<IngestionError> ingestionErrorsField;

        public PartnerItemIngestionStatus()
        {
            this.ingestionErrorsField = new List<IngestionError>();
        }

        public int martId
        {
            get
            {
                return this.martIdField;
            }
            set
            {
                this.martIdField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool martIdSpecified
        {
            get
            {
                return this.martIdFieldSpecified;
            }
            set
            {
                this.martIdFieldSpecified = value;
            }
        }

        public string sku
        {
            get
            {
                return this.skuField;
            }
            set
            {
                this.skuField = value;
            }
        }

        public string wpid
        {
            get
            {
                return this.wpidField;
            }
            set
            {
                this.wpidField = value;
            }
        }

        public int index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indexSpecified
        {
            get
            {
                return this.indexFieldSpecified;
            }
            set
            {
                this.indexFieldSpecified = value;
            }
        }

        public ItemStatus ingestionStatus
        {
            get
            {
                return this.ingestionStatusField;
            }
            set
            {
                this.ingestionStatusField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("ingestionError", IsNullable = false)]
        public List<IngestionError> ingestionErrors
        {
            get
            {
                return this.ingestionErrorsField;
            }
            set
            {
                this.ingestionErrorsField = value;
            }
        }
    }

    public enum ItemStatus
    {

        /// <remarks/>
        INPROGRESS,

        /// <remarks/>
        SUCCESS,

        /// <remarks/>
        DATA_ERROR,

        /// <remarks/>
        SYSTEM_ERROR,

        /// <remarks/>
        TIMEOUT_ERROR,
    }
}
