// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>Royal.Walmart.Order</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Royal.Walmart.Api.Model.Order
{
    using System.Collections.Generic;
    using System.Xml.Serialization;

    [XmlRoot(Namespace = "http://walmart.com/mp/v3/orders", ElementName = "order", DataType = "string", IsNullable = true)]
    //[XmlRoot("Order", Namespace = "http://walmart.com/")]
    public partial class Order
    {

        private string purchaseOrderIdField;

        private string customerOrderIdField;

        private string customerEmailIdField;

        private System.DateTime orderDateField;

        private shippingInfoType shippingInfoField;

        private List<orderLineType> orderLinesField;

        public Order()
        {
            this.orderLinesField = new List<orderLineType>();
            this.shippingInfoField = new shippingInfoType();
        }

        public string purchaseOrderId
        {
            get
            {
                return this.purchaseOrderIdField;
            }
            set
            {
                this.purchaseOrderIdField = value;
            }
        }

        public string customerOrderId
        {
            get
            {
                return this.customerOrderIdField;
            }
            set
            {
                this.customerOrderIdField = value;
            }
        }

        public string customerEmailId
        {
            get
            {
                return this.customerEmailIdField;
            }
            set
            {
                this.customerEmailIdField = value;
            }
        }

        public System.DateTime orderDate
        {
            get
            {
                return this.orderDateField;
            }
            set
            {
                this.orderDateField = value;
            }
        }

        public shippingInfoType shippingInfo
        {
            get
            {
                return this.shippingInfoField;
            }
            set
            {
                this.shippingInfoField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("orderLine", IsNullable = false)]
        public List<orderLineType> orderLines
        {
            get
            {
                return this.orderLinesField;
            }
            set
            {
                this.orderLinesField = value;
            }
        }
    }



    public partial class shippingInfoType
    {

        private string phoneField;

        private System.DateTime estimatedDeliveryDateField;

        private System.DateTime estimatedShipDateField;

        private shippingMethodCodeType methodCodeField;

        private postalAddressType postalAddressField;

        public shippingInfoType()
        {
            this.postalAddressField = new postalAddressType();
        }

        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }

        public System.DateTime estimatedDeliveryDate
        {
            get
            {
                return this.estimatedDeliveryDateField;
            }
            set
            {
                this.estimatedDeliveryDateField = value;
            }
        }

        public System.DateTime estimatedShipDate
        {
            get
            {
                return this.estimatedShipDateField;
            }
            set
            {
                this.estimatedShipDateField = value;
            }
        }

        public shippingMethodCodeType methodCode
        {
            get
            {
                return this.methodCodeField;
            }
            set
            {
                this.methodCodeField = value;
            }
        }

        public postalAddressType postalAddress
        {
            get
            {
                return this.postalAddressField;
            }
            set
            {
                this.postalAddressField = value;
            }
        }
    }

    public enum shippingMethodCodeType
    {

        /// <remarks/>
        Standard,

        /// <remarks/>
        Express,

        /// <remarks/>
        OneDay,

        /// <remarks/>
        Freight,

        /// <remarks/>
        WhiteGlove,

        /// <remarks/>
        Value,
    }

    public partial class postalAddressType
    {

        private string nameField;

        private string address1Field;

        private string address2Field;

        private string cityField;

        private string stateField;

        private string postalCodeField;

        private string countryField;

        private string addressTypeField;

        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public string address1
        {
            get
            {
                return this.address1Field;
            }
            set
            {
                this.address1Field = value;
            }
        }

        public string address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }

        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        public string postalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        public string addressType
        {
            get
            {
                return this.addressTypeField;
            }
            set
            {
                this.addressTypeField = value;
            }
        }
    }

    public partial class refundChargeType
    {

        private reasonCodesType refundReasonField;

        private chargeType chargeField;

        public refundChargeType()
        {
            this.chargeField = new chargeType();
        }

        public reasonCodesType refundReason
        {
            get
            {
                return this.refundReasonField;
            }
            set
            {
                this.refundReasonField = value;
            }
        }

        public chargeType charge
        {
            get
            {
                return this.chargeField;
            }
            set
            {
                this.chargeField = value;
            }
        }
    }

    public enum reasonCodesType
    {

        /// <remarks/>
        BillingError,

        /// <remarks/>
        TaxExemptCustomer,

        /// <remarks/>
        ItemNotAsAdvertised,

        /// <remarks/>
        IncorrectItemReceived,

        /// <remarks/>
        CancelledYetShipped,

        /// <remarks/>
        ItemNotReceivedByCustomer,

        /// <remarks/>
        IncorrectShippingPrice,

        /// <remarks/>
        DamagedItem,

        /// <remarks/>
        DefectiveItem,

        /// <remarks/>
        CustomerChangedMind,

        /// <remarks/>
        CustomerReceivedItemLate,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Missing Parts / Instructions")]
        MissingPartsInstructions,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Finance -> Goodwill")]
        FinanceGoodwill,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Finance -> Rollback")]
        FinanceRollback,

        Others
    }

    public partial class chargeType
    {

        private string chargeType1Field;

        private string chargeNameField;

        private moneyType chargeAmountField;

        private taxType taxField;

        public chargeType()
        {
            this.taxField = new taxType();
            this.chargeAmountField = new moneyType();
        }

        public string chargeType1
        {
            get
            {
                return this.chargeType1Field;
            }
            set
            {
                this.chargeType1Field = value;
            }
        }

        public string chargeName
        {
            get
            {
                return this.chargeNameField;
            }
            set
            {
                this.chargeNameField = value;
            }
        }

        public moneyType chargeAmount
        {
            get
            {
                return this.chargeAmountField;
            }
            set
            {
                this.chargeAmountField = value;
            }
        }

        public taxType tax
        {
            get
            {
                return this.taxField;
            }
            set
            {
                this.taxField = value;
            }
        }
    }

    public partial class moneyType
    {

        private currencyType currencyField;

        private decimal amountField;

        public currencyType currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }

        public decimal amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
    }

    public enum currencyType
    {

        /// <remarks/>
        AED,

        /// <remarks/>
        AFN,

        /// <remarks/>
        ALL,

        /// <remarks/>
        AMD,

        /// <remarks/>
        ANG,

        /// <remarks/>
        AOA,

        /// <remarks/>
        ARS,

        /// <remarks/>
        AUD,

        /// <remarks/>
        AWG,

        /// <remarks/>
        AZN,

        /// <remarks/>
        BAM,

        /// <remarks/>
        BBD,

        /// <remarks/>
        BDT,

        /// <remarks/>
        BGN,

        /// <remarks/>
        BHD,

        /// <remarks/>
        BIF,

        /// <remarks/>
        BMD,

        /// <remarks/>
        BND,

        /// <remarks/>
        BOB,

        /// <remarks/>
        BRL,

        /// <remarks/>
        BSD,

        /// <remarks/>
        BTN,

        /// <remarks/>
        BWP,

        /// <remarks/>
        BYR,

        /// <remarks/>
        BZD,

        /// <remarks/>
        CAD,

        /// <remarks/>
        CDF,

        /// <remarks/>
        CHF,

        /// <remarks/>
        CLP,

        /// <remarks/>
        CNY,

        /// <remarks/>
        COP,

        /// <remarks/>
        CRC,

        /// <remarks/>
        CUP,

        /// <remarks/>
        CVE,

        /// <remarks/>
        CZK,

        /// <remarks/>
        DJF,

        /// <remarks/>
        DKK,

        /// <remarks/>
        DOP,

        /// <remarks/>
        DZD,

        /// <remarks/>
        EGP,

        /// <remarks/>
        ERN,

        /// <remarks/>
        ETB,

        /// <remarks/>
        EUR,

        /// <remarks/>
        FJD,

        /// <remarks/>
        FKP,

        /// <remarks/>
        GBP,

        /// <remarks/>
        GEL,

        /// <remarks/>
        GHS,

        /// <remarks/>
        GIP,

        /// <remarks/>
        GMD,

        /// <remarks/>
        GNF,

        /// <remarks/>
        GTQ,

        /// <remarks/>
        GYD,

        /// <remarks/>
        HKD,

        /// <remarks/>
        HNL,

        /// <remarks/>
        HRK,

        /// <remarks/>
        HTG,

        /// <remarks/>
        HUF,

        /// <remarks/>
        IDR,

        /// <remarks/>
        ILS,

        /// <remarks/>
        INR,

        /// <remarks/>
        IQD,

        /// <remarks/>
        IRR,

        /// <remarks/>
        ISK,

        /// <remarks/>
        JMD,

        /// <remarks/>
        JOD,

        /// <remarks/>
        JPY,

        /// <remarks/>
        KES,

        /// <remarks/>
        KGS,

        /// <remarks/>
        KHR,

        /// <remarks/>
        KMF,

        /// <remarks/>
        KPW,

        /// <remarks/>
        KRW,

        /// <remarks/>
        KWD,

        /// <remarks/>
        KYD,

        /// <remarks/>
        KZT,

        /// <remarks/>
        LAK,

        /// <remarks/>
        LBP,

        /// <remarks/>
        LKR,

        /// <remarks/>
        LRD,

        /// <remarks/>
        LSL,

        /// <remarks/>
        LTL,

        /// <remarks/>
        LVL,

        /// <remarks/>
        LYD,

        /// <remarks/>
        MAD,

        /// <remarks/>
        MDL,

        /// <remarks/>
        MGA,

        /// <remarks/>
        MKD,

        /// <remarks/>
        MMK,

        /// <remarks/>
        MNT,

        /// <remarks/>
        MOP,

        /// <remarks/>
        MRO,

        /// <remarks/>
        MUR,

        /// <remarks/>
        MVR,

        /// <remarks/>
        MWK,

        /// <remarks/>
        MXN,

        /// <remarks/>
        MYR,

        /// <remarks/>
        MZN,

        /// <remarks/>
        NAD,

        /// <remarks/>
        NGN,

        /// <remarks/>
        NIO,

        /// <remarks/>
        NOK,

        /// <remarks/>
        NPR,

        /// <remarks/>
        NZD,

        /// <remarks/>
        OMR,

        /// <remarks/>
        PAB,

        /// <remarks/>
        PEN,

        /// <remarks/>
        PGK,

        /// <remarks/>
        PHP,

        /// <remarks/>
        PKR,

        /// <remarks/>
        PLN,

        /// <remarks/>
        PYG,

        /// <remarks/>
        QAR,

        /// <remarks/>
        RON,

        /// <remarks/>
        RSD,

        /// <remarks/>
        RUB,

        /// <remarks/>
        RUR,

        /// <remarks/>
        RWF,

        /// <remarks/>
        SAR,

        /// <remarks/>
        SBD,

        /// <remarks/>
        SCR,

        /// <remarks/>
        SDG,

        /// <remarks/>
        SEK,

        /// <remarks/>
        SGD,

        /// <remarks/>
        SHP,

        /// <remarks/>
        SLL,

        /// <remarks/>
        SOS,

        /// <remarks/>
        SRD,

        /// <remarks/>
        STD,

        /// <remarks/>
        SYP,

        /// <remarks/>
        SZL,

        /// <remarks/>
        THB,

        /// <remarks/>
        TJS,

        /// <remarks/>
        TMT,

        /// <remarks/>
        TND,

        /// <remarks/>
        TOP,

        /// <remarks/>
        TRY,

        /// <remarks/>
        TTD,

        /// <remarks/>
        TWD,

        /// <remarks/>
        TZS,

        /// <remarks/>
        UAH,

        /// <remarks/>
        UGX,

        /// <remarks/>
        USD,

        /// <remarks/>
        UYU,

        /// <remarks/>
        UZS,

        /// <remarks/>
        VEF,

        /// <remarks/>
        VND,

        /// <remarks/>
        VUV,

        /// <remarks/>
        WST,

        /// <remarks/>
        XAF,

        /// <remarks/>
        XAG,

        /// <remarks/>
        XAU,

        /// <remarks/>
        XBA,

        /// <remarks/>
        XBB,

        /// <remarks/>
        XBC,

        /// <remarks/>
        XBD,

        /// <remarks/>
        XCD,

        /// <remarks/>
        XDR,

        /// <remarks/>
        XFU,

        /// <remarks/>
        XOF,

        /// <remarks/>
        XPD,

        /// <remarks/>
        XPF,

        /// <remarks/>
        XPT,

        /// <remarks/>
        XTS,

        /// <remarks/>
        XXX,

        /// <remarks/>
        YER,

        /// <remarks/>
        ZAR,

        /// <remarks/>
        ZMK,

        /// <remarks/>
        ZWL,
    }

    public partial class taxType
    {

        private string taxNameField;

        private moneyType taxAmountField;

        public taxType()
        {
            this.taxAmountField = new moneyType();
        }

        public string taxName
        {
            get
            {
                return this.taxNameField;
            }
            set
            {
                this.taxNameField = value;
            }
        }

        public moneyType taxAmount
        {
            get
            {
                return this.taxAmountField;
            }
            set
            {
                this.taxAmountField = value;
            }
        }
    }

    public partial class refundType
    {

        private string refundIdField;

        private string refundCommentsField;

        private List<refundChargeType> refundChargesField;

        public refundType()
        {
            this.refundChargesField = new List<refundChargeType>();
        }

        public string refundId
        {
            get
            {
                return this.refundIdField;
            }
            set
            {
                this.refundIdField = value;
            }
        }

        public string refundComments
        {
            get
            {
                return this.refundCommentsField;
            }
            set
            {
                this.refundCommentsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("refundCharge", IsNullable = false)]
        public List<refundChargeType> refundCharges
        {
            get
            {
                return this.refundChargesField;
            }
            set
            {
                this.refundChargesField = value;
            }
        }
    }

    public partial class carrierNameType
    {

        private object itemField;

        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    public enum carrierType
    {

        /// <remarks/>
        UPS,

        /// <remarks/>
        USPS,

        /// <remarks/>
        FedEx,

        /// <remarks/>
        Airborne,

        /// <remarks/>
        OnTrac,
    }

    public partial class trackingInfoType
    {

        private System.DateTime shipDateTimeField;

        private carrierNameType carrierNameField;

        private shippingMethodCodeType methodCodeField;

        private string trackingNumberField;

        private string trackingURLField;

        public trackingInfoType()
        {
            this.carrierNameField = new carrierNameType();
        }

        public System.DateTime shipDateTime
        {
            get
            {
                return this.shipDateTimeField;
            }
            set
            {
                this.shipDateTimeField = value;
            }
        }

        public carrierNameType carrierName
        {
            get
            {
                return this.carrierNameField;
            }
            set
            {
                this.carrierNameField = value;
            }
        }

        public shippingMethodCodeType methodCode
        {
            get
            {
                return this.methodCodeField;
            }
            set
            {
                this.methodCodeField = value;
            }
        }

        public string trackingNumber
        {
            get
            {
                return this.trackingNumberField;
            }
            set
            {
                this.trackingNumberField = value;
            }
        }

        public string trackingURL
        {
            get
            {
                return this.trackingURLField;
            }
            set
            {
                this.trackingURLField = value;
            }
        }
    }

    public partial class orderLineStatusType
    {

        private orderLineStatusValueType statusField;

        private quantityType statusQuantityField;

        private string cancellationReasonField;

        private trackingInfoType trackingInfoField;

        public orderLineStatusType()
        {
            this.trackingInfoField = new trackingInfoType();
            this.statusQuantityField = new quantityType();
        }

        public orderLineStatusValueType status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        public quantityType statusQuantity
        {
            get
            {
                return this.statusQuantityField;
            }
            set
            {
                this.statusQuantityField = value;
            }
        }

        public string cancellationReason
        {
            get
            {
                return this.cancellationReasonField;
            }
            set
            {
                this.cancellationReasonField = value;
            }
        }

        public trackingInfoType trackingInfo
        {
            get
            {
                return this.trackingInfoField;
            }
            set
            {
                this.trackingInfoField = value;
            }
        }
    }

    public enum orderLineStatusValueType
    {

        /// <remarks/>
        Created,

        /// <remarks/>
        Acknowledged,

        /// <remarks/>
        Shipped,

        /// <remarks/>
        Cancelled,

        /// <remarks/>
        Refund,
    }

    public partial class quantityType
    {

        private string unitOfMeasurementField;

        private string amountField;

        public string unitOfMeasurement
        {
            get
            {
                return this.unitOfMeasurementField;
            }
            set
            {
                this.unitOfMeasurementField = value;
            }
        }

        public string amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
    }

    public partial class itemType
    {

        private string productNameField;

        private string skuField;

        public string productName
        {
            get
            {
                return this.productNameField;
            }
            set
            {
                this.productNameField = value;
            }
        }

        public string sku
        {
            get
            {
                return this.skuField;
            }
            set
            {
                this.skuField = value;
            }
        }
    }

    public partial class orderLineType
    {

        private string lineNumberField;

        private itemType itemField;

        private List<chargeType> chargesField;

        private quantityType orderLineQuantityField;

        private System.DateTime statusDateField;

        private List<orderLineStatusType> orderLineStatusesField;

        private refundType refundField;

        public orderLineType()
        {
            this.refundField = new refundType();
            this.orderLineStatusesField = new List<orderLineStatusType>();
            this.orderLineQuantityField = new quantityType();
            this.chargesField = new List<chargeType>();
            this.itemField = new itemType();
        }

        public string lineNumber
        {
            get
            {
                return this.lineNumberField;
            }
            set
            {
                this.lineNumberField = value;
            }
        }

        public itemType item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("charge", IsNullable = false)]
        public List<chargeType> charges
        {
            get
            {
                return this.chargesField;
            }
            set
            {
                this.chargesField = value;
            }
        }

        public quantityType orderLineQuantity
        {
            get
            {
                return this.orderLineQuantityField;
            }
            set
            {
                this.orderLineQuantityField = value;
            }
        }

        public System.DateTime statusDate
        {
            get
            {
                return this.statusDateField;
            }
            set
            {
                this.statusDateField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("orderLineStatus", IsNullable = false)]
        public List<orderLineStatusType> orderLineStatuses
        {
            get
            {
                return this.orderLineStatusesField;
            }
            set
            {
                this.orderLineStatusesField = value;
            }
        }

        public refundType refund
        {
            get
            {
                return this.refundField;
            }
            set
            {
                this.refundField = value;
            }
        }
    }
    [XmlRoot(Namespace = "http://walmart.com/mp/v3/orders", ElementName = "list", DataType = "string", IsNullable = true)]
    public partial class OrdersListType
    {

        private metaType metaField;

        private List<Order> elementsField;

        public OrdersListType()
        {
            this.elementsField = new List<Order>();
            this.metaField = new metaType();
        }

        public metaType meta
        {
            get
            {
                return this.metaField;
            }
            set
            {
                this.metaField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("order")]
        public List<Order> elements
        {
            get
            {
                return this.elementsField;
            }
            set
            {
                this.elementsField = value;
            }
        }
    }

    public partial class metaType
    {

        private int totalCountField;

        private bool totalCountFieldSpecified;

        private int limitField;

        private string nextCursorField;

        public int totalCount
        {
            get
            {
                return this.totalCountField;
            }
            set
            {
                this.totalCountField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalCountSpecified
        {
            get
            {
                return this.totalCountFieldSpecified;
            }
            set
            {
                this.totalCountFieldSpecified = value;
            }
        }

        public int limit
        {
            get
            {
                return this.limitField;
            }
            set
            {
                this.limitField = value;
            }
        }

        public string nextCursor
        {
            get
            {
                return this.nextCursorField;
            }
            set
            {
                this.nextCursorField = value;
            }
        }
    }

    public partial class priceType
    {

        private float totalField;

        private priceAndTaxType retailField;

        private priceAndTaxType shippingField;

        public priceType()
        {
            this.shippingField = new priceAndTaxType();
            this.retailField = new priceAndTaxType();
        }

        public float total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }

        public priceAndTaxType retail
        {
            get
            {
                return this.retailField;
            }
            set
            {
                this.retailField = value;
            }
        }

        public priceAndTaxType shipping
        {
            get
            {
                return this.shippingField;
            }
            set
            {
                this.shippingField = value;
            }
        }
    }

    public partial class priceAndTaxType
    {

        private moneyType priceField;

        private moneyType taxField;

        public priceAndTaxType()
        {
            this.taxField = new moneyType();
            this.priceField = new moneyType();
        }

        public moneyType price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }

        public moneyType tax
        {
            get
            {
                return this.taxField;
            }
            set
            {
                this.taxField = value;
            }
        }
    }

    public partial class orderLinesType
    {

        private List<orderLineType> orderLineField;

        public orderLinesType()
        {
            this.orderLineField = new List<orderLineType>();
        }

        public List<orderLineType> orderLine
        {
            get
            {
                return this.orderLineField;
            }
            set
            {
                this.orderLineField = value;
            }
        }
    }

    public partial class orderLineStatusesType
    {

        private List<orderLineStatusType> orderLineStatusField;

        public orderLineStatusesType()
        {
            this.orderLineStatusField = new List<orderLineStatusType>();
        }

        public List<orderLineStatusType> orderLineStatus
        {
            get
            {
                return this.orderLineStatusField;
            }
            set
            {
                this.orderLineStatusField = value;
            }
        }
    }

    public partial class elementsType
    {

        private List<Order> orderField;

        public elementsType()
        {
            this.orderField = new List<Order>();
        }

        public List<Order> order
        {
            get
            {
                return this.orderField;
            }
            set
            {
                this.orderField = value;
            }
        }
    }



    [XmlRoot(ElementName = "OrderLineReq")]
    public class OrderLineReq
    {
        [XmlElement(ElementName = "lineNumber")]
        public string LineNumber { get; set; }
        [XmlElement(ElementName = "status")]
        public string Status { get; set; }
    }

    [XmlRoot(ElementName = "OrderReq")]
    public class OrderReq
    {
        [XmlElement(ElementName = "orderLine")]
        public List<OrderLineReq> OrderLine { get; set; }
    }

    [XmlRoot(ElementName = "statusQuantity", Namespace = "http://walmart.com/mp/v3/orders")]
    public partial class StatusQuantity
    {
        [XmlElement(ElementName = "unitOfMeasurement", Namespace = "http://walmart.com/mp/v3/orders")]
        public string UnitOfMeasurement { get; set; }
        [XmlElement(ElementName = "amount", Namespace = "http://walmart.com/mp/v3/orders")]
        public string Amount { get; set; }
    }

    [XmlRoot(ElementName = "orderLineStatus", Namespace = "http://walmart.com/mp/v3/orders")]
    public partial class OrderLineStatus
    {
        [XmlElement(ElementName = "status", Namespace = "http://walmart.com/mp/v3/orders")]
        public string Status { get; set; }
        [XmlElement(ElementName = "cancellationReason", Namespace = "http://walmart.com/mp/v3/orders")]
        public string CancellationReason { get; set; }
        [XmlElement(ElementName = "statusQuantity", Namespace = "http://walmart.com/mp/v3/orders")]
        public StatusQuantity StatusQuantity { get; set; }
    }

    [XmlRoot(ElementName = "orderLineStatuses", Namespace = "http://walmart.com/mp/v3/orders")]
    public partial class OrderLineStatuses
    {
        [XmlElement(ElementName = "orderLineStatus", Namespace = "http://walmart.com/mp/v3/orders")]
        public OrderLineStatus OrderLineStatus { get; set; }
    }

    [XmlRoot(ElementName = "orderLine", Namespace = "http://walmart.com/mp/v3/orders")]
    public partial class OrderLine
    {
        [XmlElement(ElementName = "lineNumber", Namespace = "http://walmart.com/mp/v3/orders")]
        public string LineNumber { get; set; }
        [XmlElement(ElementName = "orderLineStatuses", Namespace = "http://walmart.com/mp/v3/orders")]
        public OrderLineStatuses OrderLineStatuses { get; set; }
    }

    [XmlRoot(ElementName = "orderLines", Namespace = "http://walmart.com/mp/v3/orders")]
    public partial class OrderLines
    {
        [XmlElement(ElementName = "orderLine", Namespace = "http://walmart.com/mp/v3/orders")]
        public OrderLine OrderLine { get; set; }
    }

    [XmlRoot(ElementName = "orderCancellation", Namespace = "http://walmart.com/mp/v3/orders")]
    public partial class OrderCancellation
    {
        [XmlElement(ElementName = "orderLines", Namespace = "http://walmart.com/mp/v3/orders")]
        public OrderLines OrderLines { get; set; }
        [XmlAttribute(AttributeName = "ns2", Namespace = "http://www.w3.org/2000/xmlns/")]
        public string Ns2 { get; set; }
        [XmlAttribute(AttributeName = "ns3", Namespace = "http://www.w3.org/2000/xmlns/")]
        public string Ns3 { get; set; }
    }

}

