// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>Royal.Walmart.Api</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Flexi.Model.Poco.Walmart.Api
{
    using System.Collections.Generic;
    using System.Xml.Serialization;

    [XmlRoot("orderShipment", Namespace = "http://walmart.com/mp/v3/orders")]
    public partial class orderShipment
    {

        private List<shippingLineType> orderLinesField;

        public orderShipment()
        {

        }

        [System.Xml.Serialization.XmlArrayItemAttribute("orderLine", IsNullable = false)]
        public List<shippingLineType> orderLines
        {
            get
            {
                return this.orderLinesField;
            }
            set
            {
                this.orderLinesField = value;
            }
        }
    }

    public partial class shippingLineType
    {

        private string lineNumberField;

        private List<shipLineStatusType> orderLineStatusesField;

        public shippingLineType()
        {
            this.orderLineStatusesField = new List<shipLineStatusType>();
        }

        public string lineNumber
        {
            get
            {
                return this.lineNumberField;
            }
            set
            {
                this.lineNumberField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("orderLineStatus", IsNullable = false)]
        public List<shipLineStatusType> orderLineStatuses
        {
            get
            {
                return this.orderLineStatusesField;
            }
            set
            {
                this.orderLineStatusesField = value;
            }
        }
    }

    public partial class shipLineStatusType
    {

        private orderLineStatusValueType statusField;

        private quantityType statusQuantityField;

        private trackingInfoType trackingInfoField;

        public shipLineStatusType()
        {
            this.trackingInfoField = new trackingInfoType();
            this.statusQuantityField = new quantityType();
        }

        public orderLineStatusValueType status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        public quantityType statusQuantity
        {
            get
            {
                return this.statusQuantityField;
            }
            set
            {
                this.statusQuantityField = value;
            }
        }

        public trackingInfoType trackingInfo
        {
            get
            {
                return this.trackingInfoField;
            }
            set
            {
                this.trackingInfoField = value;
            }
        }
    }

    public enum orderLineStatusValueType
    {

        /// <remarks/>
        Created,

        /// <remarks/>
        Acknowledged,

        /// <remarks/>
        Shipped,

        /// <remarks/>
        Cancelled,

        /// <remarks/>
        Refund,
    }

    public partial class quantityType
    {

        private string unitOfMeasurementField;

        private string amountField;

        public string unitOfMeasurement
        {
            get
            {
                return this.unitOfMeasurementField;
            }
            set
            {
                this.unitOfMeasurementField = value;
            }
        }

        public string amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
    }

    public partial class carrierNameType
    {
        private string otherCarrierField;

        public string otherCarrier
        {
            get
            {
                return this.otherCarrierField;
            }
            set
            {
                this.otherCarrierField = value;
            }
        }
        private carrierType carrierField;

        public carrierType carrier
        {
            get
            {
                return this.carrierField;
            }
            set
            {
                this.carrierField = value;
            }
        }
    }

    public enum carrierType
    {

        /// <remarks/>
        UPS,

        /// <remarks/>
        USPS,

        /// <remarks/>
        FedEx,

        /// <remarks/>
        Airborne,

        /// <remarks/>
        OnTrac,
    }

    public partial class trackingInfoType
    {

        private string shipDateTimeField;

        private carrierNameType carrierNameField;

        private shippingMethodCodeType methodCodeField;

        private string trackingNumberField;

        private string trackingURLField;

        public trackingInfoType()
        {

        }

        public string shipDateTime
        {
            get
            {
                return this.shipDateTimeField;
            }
            set
            {
                this.shipDateTimeField = value;
            }
        }

        public carrierNameType carrierName
        {
            get
            {
                return this.carrierNameField;
            }
            set
            {
                this.carrierNameField = value;
            }
        }

        public shippingMethodCodeType methodCode
        {
            get
            {
                return this.methodCodeField;
            }
            set
            {
                this.methodCodeField = value;
            }
        }

        public string trackingNumber
        {
            get
            {
                return this.trackingNumberField;
            }
            set
            {
                this.trackingNumberField = value;
            }
        }

        public string trackingURL
        {
            get
            {
                return this.trackingURLField;
            }
            set
            {
                this.trackingURLField = value;
            }
        }
    }

    public enum shippingMethodCodeType
    {

        /// <remarks/>
        Standard,

        /// <remarks/>
        Express,

        /// <remarks/>
        OneDay,

        /// <remarks/>
        Freight,

        /// <remarks/>
        WhiteGlove,
    }

    public partial class shippingLinesType
    {

        private List<shippingLineType> orderLineField;

        public shippingLinesType()
        {
            this.orderLineField = new List<shippingLineType>();
        }

        public List<shippingLineType> orderLine
        {
            get
            {
                return this.orderLineField;
            }
            set
            {
                this.orderLineField = value;
            }
        }
    }

    public partial class shipLineStatusesType
    {

        private List<shipLineStatusType> orderLineStatusField;

        public shipLineStatusesType()
        {
            this.orderLineStatusField = new List<shipLineStatusType>();
        }

        public List<shipLineStatusType> orderLineStatus
        {
            get
            {
                return this.orderLineStatusField;
            }
            set
            {
                this.orderLineStatusField = value;
            }
        }
    }
}
